### ISSUE TITLE
Is this driver compatible with the TMP100 and/or TMP101?

### ISSUE THREAD

**Issue by twilco** [eldruin/tmp1x2-rs#1]
Thanks for writing this driver!  Was curious, is it compatible with [TMP100](http://www.ti.com/product/TMP100) and/or the [TMP101](http://www.ti.com/product/TMP101)?

**Comment by eldruin** [comment]
Hi @twilco, both devices are quite similar to tmp1x2 but the registers are somewhat different.
Are you interested in using either TMP100 or TMP101 devices?
I could create a driver for them fairly easily.

**Comment by twilco** [comment]
It's funny you say that - the reason I ask is because I was interested in writing a driver for these two devices 😄 .  My TMP100 just arrived the other day, so just wanted to see that this crate didn't work for it before diving in.

**Comment by eldruin** [comment]
I see. Sure, it is not compatible but as I said it is easy to adapt because the two devices are a bit simpler than this one. The configuration register is just one byte and there is no extended mode, for example.
You can use this driver as a starting point. It is also full of tests, that should make it easier as well. Let me know if I can help somehow else.

**Comment by twilco** [comment]
Awesome, thanks!  If I run into issues I'll reach out.

**Comment by twilco** [comment]
@eldruin I just wanted to mention that I've [finally begun](https://github.com/twilco/tmp100-tmp101) working on a driver for the TMP100 and TMP101.  I used much of your repository as a template, and called that fact out in the README - hope that's OK!

**Comment by eldruin** [comment]
@twilco Yes, the mention sounds good to me. Have fun!
